version: '3.6'

services:

  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: pass123
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /Users/szy0syz/workspace/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8190:8080

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379

  mongo:
    image: mongo:4.4.2-bionic
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /Users/szy0syz/workspace/mongodb:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8191:8081
